### ISSUE TITLE
请教一下制作中出现的问题

### ISSUE THREAD

**Issue by cccll33** [oldgerman/SCOPE-F07x#1]
首先谢谢分享，小工具设计的非常可爱。

制作过程中有些问题请教下，通道1、2 悬空时，示波页面底部显示两通道电压均为4.5V左右，接自身波形发生（2V,10KHz,0V）时，示波页面通道电压值为MAX:5V  MIN:2.2V，测量SGM8632两个输出脚电压均为0.18V，主控071cbu6，程序版本2023-0426-0233，请问以上可能是哪里的问题，该如何排查。

**Comment by cccll33** [comment]
补充：万用表测量板上两个3.3V正常，5V正常，-5V正常，1.65V正常，两路DC输出电压正常。PCB版本1.1

**Comment by cccll33** [comment]
补充2：上述测量SGM8632输出脚（1脚 7脚）电压0.18V，是在通道1、2悬空状态下。SGM8632输入引脚（2脚 6脚）电压0.2V。
另附通道1接自身波形发生（2V，10KHz，0V）图
![01](https://github.com/oldgerman/SCOPE-F07x/assets/150916441/280cc019-a1a0-430a-9809-9722c72b4d41)
![02](https://github.com/oldgerman/SCOPE-F07x/assets/150916441/f8e58171-e6b8-42a4-863b-21c489a67a37)
![03](https://github.com/oldgerman/SCOPE-F07x/assets/150916441/c4d9d0e7-cf36-4f69-a8cb-5b77e3b8af88)

**Comment by cccll33** [comment]
排查到了，是8632的输入分压电阻焊错了，发现时看着全新未拆封的5.49K陷入了沉思。焊成了54.9K.
再次感谢分享，再次表示设计的非常可爱，小巧且实用。

**Comment by oldgerman** [comment]
很高兴这个不起眼的小玩具能给你带来实用性，祝贺你下车成功哈哈，您太客气了
（不好意思哈，我的谷歌邮箱常年广告邮件淹没了，刚才整理才看见你的issue）
